import Head from "next/head";
import { ExpenseItem } from "../components/ExpenseItem/page";
import styles from "../styles/Title.module.css";

export default function Home() {
  const expenses = [
    {
      id: "e1",
      title: "Book",
      amount: 200,
      date: new Date(2022, 11, 25),
    },
    {
      id: "e4",
      title: "Heating Pillow",
      amount: 180,
      date: new Date(2022, 9, 4),
    },
    {
      id: "e3",
      title: "Lip Balm",
      amount: 20,
      date: new Date(2022, 10, 2),
    },
    {
      id: "e4",
      title: "Sanitizer",
      amount: 40,
      date: new Date(2022, 1, 1),
    },
    {
      id: "e5",
      title: "Battery",
      amount: 188,
      date: new Date(2022, 5, 5),
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Expense Tracker</h1>
      <div className={styles.expenses}>
      <ExpenseItem
        title={expenses[0].title}
        amount={expenses[0].amount}
        date={expenses[0].date}
      />
      <ExpenseItem
        title={expenses[1].title}
        amount={expenses[1].amount}
        date={expenses[1].date}
      />
      <ExpenseItem
        title={expenses[2].title}
        amount={expenses[2].amount}
        date={expenses[2].date}
      />
      <ExpenseItem
        title={expenses[3].title}
        amount={expenses[3].amount}
        date={expenses[3].date}
      />
      <ExpenseItem
        title={expenses[4].title}
        amount={expenses[4].amount}
        date={expenses[4].date}
      />
      </div>
    </>
  );
}
