import Head from "next/head";
import React, { useState } from "react";
import { ExpenseItem } from "../components/ExpenseItem";
import { ExpensesFilter } from "../components/ExpensesFilter";
import { NewExpense } from "../components/NewExpense";
import styles from "../styles/Title.module.css";

export default function Home(props) {
  const expenses = [
    {
      id: "e1",
      title: "Book",
      amount: 200,
      date: new Date(2022, 11, 25),
    },
    {
      id: "e4",
      title: "Heating Pillow",
      amount: 180,
      date: new Date(2022, 9, 4),
    },
    {
      id: "e3",
      title: "Lip Balm",
      amount: 20,
      date: new Date(2022, 10, 2),
    },
    {
      id: "e4",
      title: "Sanitizer",
      amount: 40,
      date: new Date(2022, 1, 1),
    },
    {
      id: "e5",
      title: "Battery",
      amount: 188,
      date: new Date(2022, 5, 5),
    },
  ];

  const addExpenseHandler = (expense) => {
    console.log(expense);
  };
  const [filteredYear, setFilteredYear] = useState("2022");
  const filterChangeHandler = (selectedYear) => {
    setFilteredYear(selectedYear);
  };
  return (
    <>
      <Head>
        <title>Expense Tracker- Coding Oven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Expense Tracker</h1>
      <h2 className={styles.subTitle}>by: Coding Oven</h2>
      <NewExpense onAddExpense={addExpenseHandler} />
      <div className={styles.expenses}>
        <ExpensesFilter
          selected={filteredYear}
          onChangeFilter={filterChangeHandler}
        />
        {props.items.map((expense) => (
          <ExpenseItem
            title={expense.title}
            amount={expense.amount}
            date={expense.date}
          />
        ))}
      </div>
    </>
  );
}
